config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root "grams#index"
		resources :grams do
		resources :comments, only: :create
		end
	end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gram
end

app/models/gram.rb
class Gram < ApplicationRecord
	mount_uploader :picture, PictureUploader
	validates :picture, presence: true
	belongs_to :user
	has_many :comments

	

end

app/models/user.rb
class User < ApplicationRecord
	attr_writer :login
	validates :username, presence: :true, uniqueness: { case_sensitive: false }
	validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :grams
  has_many :comments

  def login
    @login || self.username || self.email
  end

	def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    where(conditions).first
	  end
	end

	def validate_username
	  if User.where(email: username).exists?
	    errors.add(:username, :invalid)
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def render_not_found(status=:not_found)
		render plain: "#{status.to_s.titleize} :[", status: status
	end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create]
	
	def create
		@gram = Gram.find_by_id(params[:gram_id])
		if @gram.blank?
			return render_not_found if @gram.blank?
		end  
		@gram.comments.create(comment_params.merge(user: current_user))
		redirect_to root_path
	end

	private

	def comment_params
		params.require(:comment).permit(:message)
	end

end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
	before_action :get_breeds

	def index
		if params[:query]
			@grams = Gram.where("breed ILIKE ?", "%#{params[:query]}%").order("created_at DESC").paginate(:per_page => 10, :page => params[:page])
		else
			@grams = Gram.order("created_at DESC").paginate(:per_page => 10, :page => params[:page])
		end
	end

	def new
		@gram = Gram.new
	end

	def create
		@gram = current_user.grams.create(gram_params)
		if @gram.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@gram = Gram.find_by_id(params[:id])
		return render_not_found if @gram.blank?
		@comments = @gram.comments.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
	end

	def edit
		@gram = Gram.find_by_id(params[:id])
		return render_not_found if @gram.blank?
		return render_not_found(:forbidden) if @gram.user != current_user unless current_user.username == "atom"
	end

	def update
		@gram = Gram.find_by_id(params[:id])
		return render_not_found if @gram.blank?
		return render_not_found(:forbidden) if @gram.user != current_user unless current_user.username == "atom"
		@gram.update_attributes(gram_params)
		if @gram.valid?
			redirect_to root_path
		else
			return render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@gram = Gram.find_by_id(params[:id])
		return render_not_found if @gram.blank?
		return render_not_found(:forbidden) if @gram.user != current_user
		@gram.destroy
		redirect_to root_path
	end

	def get_breeds
		@breeds = []

		CSV.foreach('app/assets/breeds/breeds.csv', encoding: 'iso-8859-1:utf-8') do |row|
			@breeds << row
		end
	end

private

	def gram_params
		params.require(:gram).permit(:message, :picture, :breed)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 ml-auto mr-auto card form">
	<%= image_tag @gram.picture.url, class: 'img-fluid' %>
	<%= simple_form_for @gram do | f | %>
		<br />
		<%= f.input :breed %>
		<%= f.input :message %>
		<%= f.submit "Update", class: "my-btn" %>
	<% end %>
</div>

app/views/grams/index.html.erb
<div class="col-12 ml-auto mr-auto">
<div class="grid">
	<% @grams.each do | gram | %>
			<div class="grid-item card">
				<%= link_to gram_path(gram) do %>
					<%= image_tag gram.picture.url, class: 'img-fluid', style: 'min-width: 20%;' %>
				<% end %>
				<div class="col-12 mt-1 caption text-center">
					<% if gram.message.present? %>
						<b><%= gram.message %></b>
					<% end %>
				</div>
				<div class="text-left user mb-0 mt-0">
					<%= gram.user.username %>
				</div>
				<div class="text-left user mt-0 mb-1" style="color:black; font-weight: normal;">
					<%= gram.created_at.strftime('%B %d, %Y') %>
				</div>
				
				<% if gram.comments.present? %>
					<hr class="hr_solid mt-0" />

					<% gram.comments.order(id: :desc).limit(2).each do |comment| %>
						<div class="comment text-left col-12 mt-1">
							<span class="comment_user">
								<%= comment.user.username %><br />
							</span>
							<span class="c_message offset-1 mb-0">
								<%= comment.message %>
							</span>
						</div>
					<% end %>
					<% if gram.comments.count > 2 %>
						<%= link_to gram_path(gram) do %>
							<div class="text-right comment_user mt-0">
								See More
							</div>
						<% end %>
					<% end %>
				<% end %>
			</div>
	<% end %>
</div>
<br />

	<div class="col-12 col-sm-4 offset-sm-4 ml-auto mr-auto digg_pagination">
			<span class="col-12 ml-auto mr-auto justify-content-center">
				<%= will_paginate @grams, :container => false %>
			</span>
	</div>

</div>

<br />

app/views/grams/index2.html.erb
<div class="row">
	<% @grams.shuffle.each do | gram | %>
		<div class="col-10 offset-1 col-sm-6 offset-sm-1 col-md-3 offset-md-1 ml-auto mr-auto">
			<div class="card">
				<div class="text-right user mb-0 mt-1">
					<%= gram.user.username %>
				</div>
				<div class="text-right user mt-0 mb-1" style="color:black; font-weight: normal;">
					<%= gram.created_at.strftime('%B %d, %Y') %>
				</div>
				<%= link_to gram_path(gram) do %>
					<%= image_tag gram.picture.url, class: 'img-fluid' %>
				<% end %>
				<p class="pb-2">
					<% if gram.message.present? %>
						<%= gram.message %>
						<br />
					<% end %>
				</p>
				
				<% if gram.comments.present? %>
					<hr class="hr_solid mt-0" />

					<% gram.comments.order(id: :desc).limit(2).each do |comment| %>
						<div class="comment col-12 mt-2">
							<span class="comment_user">
								<%= comment.user.username %><br />
							</span>
							<span class="c_message offset-1 mb-0">
								<%= comment.message %>
							</span>
						</div>
					<% end %>
					<% if gram.comments.count > 2 %>
						<%= link_to gram_path(gram) do %>
							<div class="text-right comment_user mt-0">
								See All Comments
							</div>
						<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>
<br />

app/views/grams/new.html.erb
<br />
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 ml-auto mr-auto card form">
	<h2>new pic</h2>
	<%= simple_form_for @gram do |f| %>
		<br />
		<%= f.input :breed %>
		<%= f.input :message, label: 'Caption' %>
		<%= f.input :picture %>
		<br />
		<%= f.submit "share pic", class: "my-btn" %>
	<% end %>
</div>

app/views/grams/show.html.erb
<div class="col-10 offset-1 col-sm-6 offset-sm-3 ml-auto mr-auto">
	<br />
	<div class="card">
		<%= image_tag @gram.picture.url, class: 'img-fluid' %>
			<div class="col-12 mt-2 caption text-center" style="font-size:16px;">
				<% if @gram.message.present? %>
					<b><%= @gram.message %></b>
				<% end %>
			</div>
			<div class="text-left user mb-0 mt-0">
				<%= @gram.user.username %>
			</div>
			<div class="text-left user mt-0 mb-1" style="color:black; font-weight: normal;">
				<%= @gram.created_at.strftime('%B %d, %Y') %>
			</div>
		<div class="gram-actions text-right">
			<% if current_user && current_user == @gram.user || current_user && current_user.username == "atom" %>
				<br />
				<%= link_to 'Edit', edit_gram_path(@gram), class: 'btn btn-primary btn-sm btn-edit' %>
				<%= link_to 'Delete', gram_path(@gram), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm btn-delete' %>
				<br />
			<% end %>
			<br />
		</div>

		<hr />

		<div class="comments">
			<h3>Comments</h3>
			<% @comments.each do |comment| %>

				<div class="comment">
					<span class="comment_user">
						<%= comment.user.username %><br />
					</span>
					<span class="c_message offset-1">
						<%= comment.message %>
					</span>
				</div>
			<% end %>

			<%= will_paginate @comments %>
			<%= simple_form_for Comment.new, url: gram_comments_path(@gram) do |f| %>
					<br />
					<%= f.input :message, label: 'Add Comment', style: 'width: 90% !important;' %>
					<%= f.submit "Submit", class: "my-btn", style: "cursor: pointer;" %>
			<% end %>

		</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pic of the Litter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  </head>

  <body>
    <!-- Navigation Bar --> 
      <nav class="row navbar navbar-toggleable-md navbar-light", style="color:white;">
        <%= link_to root_path, class: 'logo ml-2' do %>
          <b style="color:#3e3666;">pic <span class="fas fa-paw"></span><br/> of the litter</b>
        <% end %>
        <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to new_gram_path, class: 'nav-link' do %>
                <span class="fas fa-plus-circle"></span><span class="share">&nbspnew pic</span>
              <% end %>
            </li>
          </ul>
        <% end %>


          <!-- Devise Login -->
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item signs">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
      </nav>

      <% if current_page?(root_path) %>
        <div class="row subnav">
          <h5 class="offset-1 mr-2 mt-1">Breed:</h5>
          <%= form_tag(root_path, method: :get) do %>
            <%= text_field_tag(:query, params[:query], placeholder: "Breed", class: "form-control breed") %>
            <%= submit_tag ("Go"), class: "btn btn-edit ml-2", style: "height: 30px; line-height: 1px" %>
          <% end %>
        </div>
      <% end%>

    <!-- Flash Messages -->
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %> 

    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>